export interface ITDCountry {
  code: string;
  name: string;
  dialCode: string;
  currencyCode: string | null;
}

export const ITD_COUNTRY_LIST: ITDCountry[] = [
  { code: "AF", name: "AFGHANISTAN", dialCode: "+93", currencyCode: "AFN" },
  { code: "AL", name: "ALBANIA", dialCode: "+355", currencyCode: "ALL" },
  { code: "DZ", name: "ALGERIA", dialCode: "+213", currencyCode: "DZD" },
  { code: "AS", name: "AMERICAN SAMOA", dialCode: "+1-684", currencyCode: "USD" },
  { code: "AD", name: "ANDORRA", dialCode: "+376", currencyCode: "EUR" },
  { code: "AO", name: "ANGOLA", dialCode: "+244", currencyCode: "AOA" },
  { code: "AI", name: "ANGUILLA", dialCode: "+1-264", currencyCode: "XCD" },
  { code: "AG", name: "ANTIGUA", dialCode: "+1-268", currencyCode: "XCD" },
  { code: "AR", name: "ARGENTINA", dialCode: "+54", currencyCode: "ARS" },
  { code: "AM", name: "ARMENIA", dialCode: "+374", currencyCode: "AMD" },
  { code: "AW", name: "ARUBA", dialCode: "+297", currencyCode: "AWG" },
  { code: "AU", name: "AUSTRALIA", dialCode: "+61", currencyCode: "AUD" },
  { code: "AT", name: "AUSTRIA", dialCode: "+43", currencyCode: "EUR" },
  { code: "AZ", name: "AZERBAIJAN", dialCode: "+994", currencyCode: "AZN" },
  { code: "BS", name: "BAHAMAS", dialCode: "+1-242", currencyCode: "BSD" },
  { code: "BH", name: "BAHRAIN", dialCode: "+973", currencyCode: "BHD" },
  { code: "BD", name: "BANGLADESH", dialCode: "+880", currencyCode: "BDT" },
  { code: "BB", name: "BARBADOS", dialCode: "+1-246", currencyCode: "BBD" },
  { code: "BY", name: "BELARUS", dialCode: "+375", currencyCode: "BYN" },
  { code: "BE", name: "BELGIUM", dialCode: "+32", currencyCode: "EUR" },
  { code: "BZ", name: "BELIZE", dialCode: "+501", currencyCode: "BZD" },
  { code: "BJ", name: "BENIN", dialCode: "+229", currencyCode: "XOF" },
  { code: "BM", name: "BERMUDA", dialCode: "+1-441", currencyCode: "BMD" },
  { code: "BT", name: "BHUTAN", dialCode: "+975", currencyCode: "INR" },
  { code: "BO", name: "BOLIVIA", dialCode: "+591", currencyCode: "BOB" },
  { code: "XB", name: "BONAIRE", dialCode: "+599", currencyCode: "USD" },
  { code: "BA", name: "BOSNIA AND HERZEGOVINA", dialCode: "+387", currencyCode: "BAM" },
  { code: "BW", name: "BOTSWANA", dialCode: "+267", currencyCode: "BWP" },
  { code: "BR", name: "BRAZIL", dialCode: "+55", currencyCode: "BRL" },
  { code: "BN", name: "BRUNEI", dialCode: "+673", currencyCode: "BND" },
  { code: "BG", name: "BULGARIA", dialCode: "+359", currencyCode: "EUR" },
  { code: "BF", name: "BURKINA FASO", dialCode: "+226", currencyCode: "XOF" },
  { code: "BI", name: "BURUNDI", dialCode: "+257", currencyCode: "BIF" },
  { code: "KH", name: "CAMBODIA", dialCode: "+855", currencyCode: "KHR" },
  { code: "CM", name: "CAMEROON", dialCode: "+237", currencyCode: "XAF" },
  { code: "CA", name: "CANADA", dialCode: "+1", currencyCode: "CAD" },
  { code: "IC", name: "CANARY ISLANDS, THE", dialCode: "", currencyCode: null },
  { code: "CV", name: "CAPE VERDE", dialCode: "+238", currencyCode: "CVE" },
  { code: "KY", name: "CAYMAN ISLANDS", dialCode: "+1-345", currencyCode: "KYD" },
  { code: "CF", name: "CENTRAL AFRICAN REPUBLIC", dialCode: "+236", currencyCode: "XAF" },
  { code: "TD", name: "CHAD", dialCode: "+235", currencyCode: "XAF" },
  { code: "CL", name: "CHILE", dialCode: "+56", currencyCode: "CLP" },
  { code: "CN", name: "CHINA, PEOPLES REPUBLIC", dialCode: "+86", currencyCode: "CNY" },
  { code: "CO", name: "COLOMBIA", dialCode: "+57", currencyCode: "COP" },
  { code: "KM", name: "COMOROS", dialCode: "+269", currencyCode: "KMF" },
  { code: "CG", name: "CONGO", dialCode: "+242", currencyCode: "XAF" },
  { code: "CD", name: "CONGO, THE DEMOCRATIC REPUBLIC", dialCode: "+243", currencyCode: "CDF" },
  { code: "CK", name: "COOK ISLANDS", dialCode: "+682", currencyCode: "NZD" },
  { code: "CR", name: "COSTA RICA", dialCode: "+506", currencyCode: "CRC" },
  { code: "CI", name: "COTE DIVOIRE", dialCode: "+225", currencyCode: "XOF" },
  { code: "HR", name: "CROATIA", dialCode: "+385", currencyCode: "EUR" },
  { code: "CU", name: "CUBA", dialCode: "+53", currencyCode: "CUP" },
  { code: "XC", name: "CURACAO", dialCode: "+599", currencyCode: "ANG" },
  { code: "CY", name: "CYPRUS", dialCode: "+357", currencyCode: "EUR" },
  { code: "CZ", name: "CZECH REPUBLIC, THE", dialCode: "+420", currencyCode: "CZK" },
  { code: "DK", name: "DENMARK", dialCode: "+45", currencyCode: "DKK" },
  { code: "DJ", name: "DJIBOUTI", dialCode: "+253", currencyCode: "DJF" },
  { code: "DM", name: "DOMINICA", dialCode: "+1-767", currencyCode: "XCD" },
  { code: "DO", name: "DOMINICAN REPUBLIC", dialCode: "+1-809", currencyCode: "DOP" },
  { code: "TL", name: "EAST TIMOR", dialCode: "+670", currencyCode: "USD" },
  { code: "EC", name: "ECUADOR", dialCode: "+593", currencyCode: "USD" },
  { code: "EG", name: "EGYPT", dialCode: "+20", currencyCode: "EGP" },
  { code: "SV", name: "EL SALVADOR", dialCode: "+503", currencyCode: "SVC" },
  { code: "ER", name: "ERITREA", dialCode: "+291", currencyCode: "ERN" },
  { code: "EE", name: "ESTONIA", dialCode: "+372", currencyCode: "EUR" },
  { code: "ET", name: "ETHIOPIA", dialCode: "+251", currencyCode: "ETB" },
  { code: "FK", name: "FALKLAND ISLANDS", dialCode: "+500", currencyCode: "FKP" },
  { code: "FO", name: "FAROE ISLANDS", dialCode: "+298", currencyCode: "DKK" },
  { code: "FJ", name: "FIJI", dialCode: "+679", currencyCode: "FJD" },
  { code: "FI", name: "FINLAND", dialCode: "+358", currencyCode: "EUR" },
  { code: "FR", name: "FRANCE", dialCode: "+33", currencyCode: "EUR" },
  { code: "GF", name: "FRENCH GUYANA", dialCode: "+594", currencyCode: "EUR" },
  { code: "GA", name: "GABON", dialCode: "+241", currencyCode: "XAF" },
  { code: "GM", name: "GAMBIA", dialCode: "+220", currencyCode: "GMD" },
  { code: "GE", name: "GEORGIA", dialCode: "+995", currencyCode: "GEL" },
  { code: "DE", name: "GERMANY", dialCode: "+49", currencyCode: "EUR" },
  { code: "GH", name: "GHANA", dialCode: "+233", currencyCode: "GHS" },
  { code: "GI", name: "GIBRALTAR", dialCode: "+350", currencyCode: "GIP" },
  { code: "GR", name: "GREECE", dialCode: "+30", currencyCode: "EUR" },
  { code: "GL", name: "GREENLAND", dialCode: "+299", currencyCode: "DKK" },
  { code: "GD", name: "GRENADA", dialCode: "+1-473", currencyCode: "XCD" },
  { code: "GP", name: "GUADELOUPE", dialCode: "+590", currencyCode: "EUR" },
  { code: "GU", name: "GUAM", dialCode: "+1-671", currencyCode: "USD" },
  { code: "GT", name: "GUATEMALA", dialCode: "+502", currencyCode: "GTQ" },
  { code: "GG", name: "GUERNSEY", dialCode: "+44", currencyCode: "GBP" },
  { code: "GN", name: "GUINEA REPUBLIC", dialCode: "+224", currencyCode: "GNF" },
  { code: "GW", name: "GUINEA-BISSAU", dialCode: "+245", currencyCode: "XOF" },
  { code: "GQ", name: "GUINEA-EQUATORIAL", dialCode: "+240", currencyCode: "XAF" },
  { code: "GY", name: "GUYANA (BRITISH)", dialCode: "+592", currencyCode: "GYD" },
  { code: "HT", name: "HAITI", dialCode: "+509", currencyCode: "HTG" },
  { code: "HN", name: "HONDURAS", dialCode: "+504", currencyCode: "HNL" },
  { code: "HK", name: "HONG KONG", dialCode: "+852", currencyCode: "HKD" },
  { code: "HU", name: "HUNGARY", dialCode: "+36", currencyCode: "HUF" },
  { code: "IS", name: "ICELAND", dialCode: "+354", currencyCode: "ISK" },
  { code: "IN", name: "INDIA", dialCode: "+91", currencyCode: "INR" },
  { code: "ID", name: "INDONESIA", dialCode: "+62", currencyCode: "IDR" },
  { code: "IR", name: "IRAN (ISLAMIC REPUBLIC OF)", dialCode: "+98", currencyCode: "IRR" },
  { code: "IQ", name: "IRAQ", dialCode: "+964", currencyCode: "IQD" },
  { code: "IE", name: "IRELAND, REPUBLIC OF", dialCode: "+353", currencyCode: "EUR" },
  { code: "IL", name: "ISRAEL", dialCode: "+972", currencyCode: "ILS" },
  { code: "IT", name: "ITALY", dialCode: "+39", currencyCode: "EUR" },
  { code: "JM", name: "JAMAICA", dialCode: "+1-876", currencyCode: "JMD" },
  { code: "JP", name: "JAPAN", dialCode: "+81", currencyCode: "JPY" },
  { code: "JE", name: "JERSEY", dialCode: "+44", currencyCode: "GBP" },
  { code: "JO", name: "JORDAN", dialCode: "+962", currencyCode: "JOD" },
  { code: "KZ", name: "KAZAKHSTAN", dialCode: "+7", currencyCode: "KZT" },
  { code: "KE", name: "KENYA", dialCode: "+254", currencyCode: "KES" },
  { code: "KI", name: "KIRIBATI", dialCode: "+686", currencyCode: "AUD" },
  { code: "KR", name: "KOREA, REPUBLIC OF", dialCode: "+82", currencyCode: "KRW" },
  { code: "KP", name: "KOREA, THE D.P.R OF", dialCode: "+850", currencyCode: "KPW" },
  { code: "KV", name: "KOSOVO", dialCode: "", currencyCode: null },
  { code: "KW", name: "KUWAIT", dialCode: "+965", currencyCode: "KWD" },
  { code: "KG", name: "KYRGYZSTAN", dialCode: "+996", currencyCode: "KGS" },
  { code: "LA", name: "LAO PEOPLES DEMOCRATIC REPUBLIC", dialCode: "+856", currencyCode: "LAK" },
  { code: "LV", name: "LATVIA", dialCode: "+371", currencyCode: "EUR" },
  { code: "LB", name: "LEBANON", dialCode: "+961", currencyCode: "LBP" },
  { code: "LS", name: "LESOTHO", dialCode: "+266", currencyCode: "LSL" },
  { code: "LR", name: "LIBERIA", dialCode: "+231", currencyCode: "LRD" },
  { code: "LY", name: "LIBYA", dialCode: "+218", currencyCode: "LYD" },
  { code: "LI", name: "LIECHTENSTEIN", dialCode: "+423", currencyCode: "CHF" },
  { code: "LT", name: "LITHUANIA", dialCode: "+370", currencyCode: "EUR" },
  { code: "LU", name: "LUXEMBOURG", dialCode: "+352", currencyCode: "EUR" },
  { code: "MO", name: "MACAU", dialCode: "+853", currencyCode: "MOP" },
  { code: "MK", name: "MACEDONIA, REPUBLIC OF", dialCode: "+389", currencyCode: "MKD" },
  { code: "MG", name: "MADAGASCAR", dialCode: "+261", currencyCode: "MGA" },
  { code: "MW", name: "MALAWI", dialCode: "+265", currencyCode: "MWK" },
  { code: "MY", name: "MALAYSIA", dialCode: "+60", currencyCode: "MYR" },
  { code: "MV", name: "MALDIVES", dialCode: "+960", currencyCode: "MVR" },
  { code: "ML", name: "MALI", dialCode: "+223", currencyCode: "XOF" },
  { code: "MT", name: "MALTA", dialCode: "+356", currencyCode: "EUR" },
  { code: "MH", name: "MARSHALL ISLANDS", dialCode: "+692", currencyCode: "USD" },
  { code: "MQ", name: "MARTINIQUE", dialCode: "+596", currencyCode: "EUR" },
  { code: "MR", name: "MAURITANIA", dialCode: "+222", currencyCode: "MRU" },
  { code: "MU", name: "MAURITIUS", dialCode: "+230", currencyCode: "MUR" },
  { code: "YT", name: "MAYOTTE", dialCode: "+262", currencyCode: "EUR" },
  { code: "MX", name: "MEXICO", dialCode: "+52", currencyCode: "MXN" },
  { code: "FM", name: "MICRONESIA, FEDERATED STATES OF", dialCode: "+691", currencyCode: "USD" },
  { code: "MD", name: "MOLDOVA, REPUBLIC OF", dialCode: "+373", currencyCode: "MDL" },
  { code: "MC", name: "MONACO", dialCode: "+377", currencyCode: "EUR" },
  { code: "MN", name: "MONGOLIA", dialCode: "+976", currencyCode: "MNT" },
  { code: "ME", name: "MONTENEGRO, REPUBLIC OF", dialCode: "+382", currencyCode: "EUR" },
  { code: "MS", name: "MONTSERRAT", dialCode: "+1-664", currencyCode: "XCD" },
  { code: "MA", name: "MOROCCO", dialCode: "+212", currencyCode: "MAD" },
  { code: "MZ", name: "MOZAMBIQUE", dialCode: "+258", currencyCode: "MZN" },
  { code: "MM", name: "MYANMAR", dialCode: "+95", currencyCode: "MMK" },
  { code: "nan", name: "NAMIBIA", dialCode: "+264", currencyCode: "NAD" },
  { code: "NR", name: "NAURU, REPUBLIC OF", dialCode: "+674", currencyCode: "AUD" },
  { code: "NP", name: "NEPAL", dialCode: "+977", currencyCode: "NPR" },
  { code: "NL", name: "NETHERLANDS, THE", dialCode: "+31", currencyCode: "EUR" },
  { code: "XN", name: "NEVIS", dialCode: "+869", currencyCode: "USD" },
  { code: "NC", name: "NEW CALEDONIA", dialCode: "+687", currencyCode: "XPF" },
  { code: "NZ", name: "NEW ZEALAND", dialCode: "+64", currencyCode: "NZD" },
  { code: "NI", name: "NICARAGUA", dialCode: "+505", currencyCode: "NIO" },
  { code: "NE", name: "NIGER", dialCode: "+227", currencyCode: "XOF" },
  { code: "NG", name: "NIGERIA", dialCode: "+234", currencyCode: "NGN" },
  { code: "NU", name: "NIUE", dialCode: "+683", currencyCode: "NZD" },
  { code: "NO", name: "NORWAY", dialCode: "+47", currencyCode: "NOK" },
  { code: "OM", name: "OMAN", dialCode: "+968", currencyCode: "OMR" },
  { code: "PK", name: "PAKISTAN", dialCode: "+92", currencyCode: "PKR" },
  { code: "PW", name: "PALAU", dialCode: "+680", currencyCode: "USD" },
  { code: "PA", name: "PANAMA", dialCode: "+507", currencyCode: "PAB" },
  { code: "PG", name: "PAPUA NEW GUINEA", dialCode: "+675", currencyCode: "PGK" },
  { code: "PY", name: "PARAGUAY", dialCode: "+595", currencyCode: "PYG" },
  { code: "PE", name: "PERU", dialCode: "+51", currencyCode: "PEN" },
  { code: "PH", name: "PHILIPPINES, THE", dialCode: "+63", currencyCode: "PHP" },
  { code: "PL", name: "POLAND", dialCode: "+48", currencyCode: "PLN" },
  { code: "PT", name: "PORTUGAL", dialCode: "+351", currencyCode: "EUR" },
  { code: "PR", name: "PUERTO RICO", dialCode: "+1", currencyCode: "USD" },
  { code: "QA", name: "QATAR", dialCode: "+974", currencyCode: "QAR" },
  { code: "RE", name: "REUNION, ISLAND OF", dialCode: "+262", currencyCode: "EUR" },
  { code: "RO", name: "ROMANIA", dialCode: "+40", currencyCode: "RON" },
  { code: "RU", name: "RUSSIAN FEDERATION, THE", dialCode: "+7", currencyCode: "RUB" },
  { code: "RW", name: "RWANDA", dialCode: "+250", currencyCode: "RWF" },
  { code: "SH", name: "SAINT HELENA", dialCode: "+290 n", currencyCode: "SHP" },
  { code: "MP", name: "SAIPAN", dialCode: "+1-670", currencyCode: "USD" },
  { code: "WS", name: "SAMOA", dialCode: "+685", currencyCode: "WST" },
  { code: "SM", name: "SAN MARINO", dialCode: "+378", currencyCode: "EUR" },
  { code: "ST", name: "SAO TOME AND PRINCIPE", dialCode: "+239", currencyCode: "STN" },
  { code: "SA", name: "SAUDI ARABIA", dialCode: "+966", currencyCode: "SAR" },
  { code: "SN", name: "SENEGAL", dialCode: "+221", currencyCode: "XOF" },
  { code: "RS", name: "SERBIA, REPUBLIC OF", dialCode: "+381 p", currencyCode: "RSD" },
  { code: "SC", name: "SEYCHELLES", dialCode: "+248", currencyCode: "SCR" },
  { code: "SL", name: "SIERRA LEONE", dialCode: "+232", currencyCode: "SLE" },
  { code: "SG", name: "SINGAPORE", dialCode: "+65", currencyCode: "SGD" },
  { code: "SK", name: "SLOVAKIA", dialCode: "+421", currencyCode: "EUR" },
  { code: "SI", name: "SLOVENIA", dialCode: "+386", currencyCode: "EUR" },
  { code: "SB", name: "SOLOMON ISLANDS", dialCode: "+677", currencyCode: "SBD" },
  { code: "SO", name: "SOMALIA", dialCode: "+252", currencyCode: "SOS" },
  { code: "XS", name: "SOMALILAND, REP OF (NORTH SOMALIA)", dialCode: "+252", currencyCode: "USD" },
  { code: "ZA", name: "SOUTH AFRICA", dialCode: "+27", currencyCode: "ZAR" },
  { code: "SS", name: "SOUTH SUDAN", dialCode: "+211", currencyCode: "SSP" },
  { code: "ES", name: "SPAIN", dialCode: "+34", currencyCode: "EUR" },
  { code: "LK", name: "SRI LANKA", dialCode: "+94", currencyCode: "LKR" },
  { code: "XY", name: "ST. BARTHELEMY", dialCode: "+590", currencyCode: "EUR" },
  { code: "XE", name: "ST. EUSTATIUS", dialCode: "+599", currencyCode: "USD" },
  { code: "KN", name: "ST. KITTS", dialCode: "+1-869", currencyCode: "XCD" },
  { code: "LC", name: "ST. LUCIA", dialCode: "+1-758", currencyCode: "XCD" },
  { code: "XM", name: "ST. MAARTEN", dialCode: "+721", currencyCode: "ANG" },
  { code: "VC", name: "ST. VINCENT", dialCode: "+1-784", currencyCode: "XCD" },
  { code: "SD", name: "SUDAN", dialCode: "+249", currencyCode: "SDG" },
  { code: "SR", name: "SURINAME", dialCode: "+597", currencyCode: "SRD" },
  { code: "SZ", name: "SWAZILAND", dialCode: "+268", currencyCode: "SZL" },
  { code: "SE", name: "SWEDEN", dialCode: "+46", currencyCode: "SEK" },
  { code: "CH", name: "SWITZERLAND", dialCode: "+41", currencyCode: "CHF" },
  { code: "SY", name: "SYRIA", dialCode: "+963", currencyCode: "SYP" },
  { code: "PF", name: "TAHITI", dialCode: "+689", currencyCode: "XPF" },
  { code: "TW", name: "TAIWAN", dialCode: "+886", currencyCode: "TWD" },
  { code: "TJ", name: "TAJIKISTAN", dialCode: "+992", currencyCode: "TJS" },
  { code: "TZ", name: "TANZANIA", dialCode: "+255", currencyCode: "TZS" },
  { code: "TH", name: "THAILAND", dialCode: "+66", currencyCode: "THB" },
  { code: "TG", name: "TOGO", dialCode: "+228", currencyCode: "XOF" },
  { code: "TO", name: "TONGA", dialCode: "+676", currencyCode: "TOP" },
  { code: "TT", name: "TRINIDAD AND TOBAGO", dialCode: "+1-868", currencyCode: "TTD" },
  { code: "TN", name: "TUNISIA", dialCode: "+216", currencyCode: "TND" },
  { code: "TR", name: "TURKEY", dialCode: "+90", currencyCode: "TRY" },
  { code: "TM", name: "TURKMENISTAN", dialCode: "+993", currencyCode: "TMT" },
  { code: "TC", name: "TURKS AND CAICOS ISLANDS", dialCode: "+1-649", currencyCode: "USD" },
  { code: "TV", name: "TUVALU", dialCode: "+688", currencyCode: "AUD" },
  { code: "UG", name: "UGANDA", dialCode: "+256", currencyCode: "UGX" },
  { code: "UA", name: "UKRAINE", dialCode: "+380", currencyCode: "UAH" },
  { code: "AE", name: "UNITED ARAB EMIRATES", dialCode: "+971", currencyCode: "AED" },
  { code: "GB", name: "UNITED KINGDOM", dialCode: "+44", currencyCode: "GBP" },
  { code: "US", name: "UNITED STATES", dialCode: "+1", currencyCode: "USD" },
  { code: "UY", name: "URUGUAY", dialCode: "+598", currencyCode: "UYU" },
  { code: "UZ", name: "UZBEKISTAN", dialCode: "+998", currencyCode: "UZS" },
  { code: "VU", name: "VANUATU", dialCode: "+678", currencyCode: "VUV" },
  { code: "VA", name: "VATICAN CITY STATE", dialCode: "+39-06", currencyCode: "EUR" },
  { code: "VE", name: "VENEZUELA", dialCode: "+58", currencyCode: "VES" },
  { code: "VN", name: "VIETNAM", dialCode: "+84", currencyCode: "VND" },
  { code: "VG", name: "VIRGIN ISLANDS (BRITISH)", dialCode: "+1-284", currencyCode: "USD" },
  { code: "VI", name: "VIRGIN ISLANDS (US)", dialCode: "+1-340", currencyCode: "USD" },
  { code: "YE", name: "YEMEN, REPUBLIC OF", dialCode: "+967", currencyCode: "YER" },
  { code: "ZM", name: "ZAMBIA", dialCode: "+260", currencyCode: "ZMW" },
  { code: "ZW", name: "ZIMBABWE", dialCode: "+263", currencyCode: "ZWG" },
];

export const ITD_COUNTRY_MAP: Record<string, ITDCountry> = Object.fromEntries(
  ITD_COUNTRY_LIST.map((c) => [c.code, c])
);

export function getDestinationCurrency(code: string): string | null {
  return ITD_COUNTRY_MAP[code]?.currencyCode ?? null;
}

/** Title-case ALL CAPS country names from ITD list for display. */
export function formatCountryDisplay(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/(^|[\s,]+)([a-z])/g, (_m, sep, letter) => sep + letter.toUpperCase());
}
